name: Entrega Contínua

on:
 workflow_call:

jobs:

  OracleCloud:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - name: ssh deploy
          # You may pin to the exact commit or the version.
          # uses: easingthemes/ssh-deploy@01a39e33483634cbd7ac99020c55b72ca7f098fe
           uses: easingthemes/ssh-deploy@v5.0.3
           with:
             SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              # Remote host
             REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
              # Remote user
             REMOTE_USER: ${{ secrets.REMOTE_USER }}
              # Remote port
             TARGET: /home/${{ secrets.REMOTE_USER }}
             EXCLUDE: "postgre-data"

         - name: executing remote ssh commands using password
           uses: appleboy/ssh-action@v1.0.3
           with:
             host: ${{ secrets.REMOTE_HOST }}
             username: ${{ secrets.REMOTE_USER }}
             key: ${{ secrets.SSH_PRIVATE_KEY }}
             port: 22
             script: |
               export HOST=${{ secrets.DB_HOST }}
               export USER=${{ secrets.DB_USER }}
               export PASSWORD=${{ secrets.DB_PASSWORD }}
               export DBNAME=${{ secrets.DB_NAME }}
               export DBPORT=${{ secrets.DB_PORT }}
               export PORT=8000
               chmod +x main
               nohup ./main &
               nohup .main > nohup.out 2> nohup.err < /dev/null &
               
